### ISSUE TITLE
BUG MYSQL

### ISSUE THREAD

**Issue by rdrhgameur** [Roytreo28/UltimateSheepWars#10]
1. Certains joueurs peuvent perdre leur données de jeu et par conséquent se retrouver à 0 sans aucune raison
2. Certains joueurs peuvent se retrouver en double dans la base de données et du coup fausser tout ce qui est classement et tops

**Comment by Roytreo28** [comment]
Ce problème est étrange. Étant donné que je dois rénover le système de base de données, j'ose espérer que ce sera réglé avec. Cependant, si vous avez d'autres indices, cela m’intéresse.

**Comment by rdrhgameur** [comment]
Malheureusement cela se produit sans laissé de traces dans les logs
